### ISSUE TITLE
Responsive Side menu, Items Missing or not in view.

### ISSUE THREAD

**Issue by Snow4k-Azura** [indiehd/docs#9]
When shortening the sites width down, the side menu items disappear. This problem is crucial as the menu is needed to navigate the site, rendering it useless if it disappears on mobile version.

**Comment by poppabear8883** [comment]
Mobile menu's are activate using the `3 bar button` which is very typical for mobile apps. It is located in the bottom left hand corner of the browser:
![image](https://user-images.githubusercontent.com/7263458/45921508-ef076580-be84-11e8-908d-b51527ca4992.png)
^ `3 bar button`

**Comment by Snow4k-Azura** [comment]
Ok then it works now, I tried it on a PC browser, thats probably why is bugged out.
